# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

                     - name: Vale Linter
  # You may pin to the exact commit or the version.
  # uses: errata-ai/vale-action@38bf078c328061f59879b347ca344a718a736018
  uses: errata-ai/vale-action@v2.1.0
  with:
    # The Vale CLI version to install.
    version: # optional, default is latest
    # The files to lint: "all" or "<some_folder>".
    files: # optional, default is all
    # Log debugging information to stdout.
    debug: # optional, default is false
    # Reporter of reviewdog command [github-pr-check,github-pr-review,github-pr-annotations,github-check].
    reporter: # optional, default is github-pr-annotations
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Report level for reviewdog [info,warning,error].
    level: # optional, default is error
    # Filtering for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Space-delimited list of flags for the Vale CLI.
    vale_flags: # optional, default is 
    # Split character for input strings.
    separator: # optional, default is 
    # The URL to a tar.gz build of reviewdog to use in the action
    reviewdog_url: # optional, default is 
    # The GitHub token to use.
    token: # optional, default is ${{ github.token }}
           
